"""
Django settings for weba1 project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from celery.schedules import crontab
from pytz import timezone
from .password import PassDevelA1Hub, PassDevelIntranet, PassMasterA1Hub, PassMasterIntranet, PassMasterDMPAcesso, PassMasterGLPI
from kombu import Queue, Exchange

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('A1_SECRET_KEY', 'django-insecure-fallback-key-change-in-production')
ti_email = 'ti@a1.com.br'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# flag para ser alterada quando o banco for para a produção
DEVEL = os.environ['A1_HUB_ENV']
EMAIL_DEBUG = os.environ['A1_HUB_DEBUG_EMAIL']
BLOCK_ROBODOC = True if 'S' in str(os.environ['A1_HUB_BLOCK_ROBODOC']).upper() else False
ROBODOC_MAX_REQUEST = int(os.environ['A1_HUB_ROBODOC_MAX_REQUEST'])

HOST = 'localhost'
if DEVEL == 'dev' and HOST == 'localhost':
    HOST = PassDevelA1Hub.host

if DEVEL == 'dev':
    DEBUG = True  # Mantem static dos apps disponivel no runserver local
    host_hub = HOST  # PassDevelA1Hub.host
    password_hub = PassDevelA1Hub.password
    user_hub = PassDevelIntranet.user
    host_intra = PassDevelIntranet.host
    password_intra = PassDevelIntranet.password
    user_intra = PassDevelIntranet.user
    host_catraca = PassMasterDMPAcesso.host
    password_catraca = PassMasterDMPAcesso.password
    user_catraca = PassMasterDMPAcesso.user
    host_glpi = PassMasterGLPI.host
    password_glpi = PassMasterGLPI.password
    user_glpi = PassMasterGLPI.user
else:
    host_hub = HOST  # PassMasterA1Hub.host
    password_hub = PassMasterA1Hub.password
    user_hub = PassMasterA1Hub.user
    host_intra = PassMasterIntranet.host
    password_intra = PassMasterIntranet.password
    user_intra = PassMasterIntranet.user
    host_catraca = PassMasterDMPAcesso.host
    password_catraca = PassMasterDMPAcesso.password
    user_catraca = PassMasterDMPAcesso.user
    host_glpi = PassMasterGLPI.host
    password_glpi = PassMasterGLPI.password
    user_glpi = PassMasterGLPI.user


CELERY_RESULT_EXTENDED = True

# Opcional: em desenvolvimento, permitir conexao sem senha (para MySQL local sem password)
if DEVEL == 'dev' and str(os.environ.get('A1_HUB_DB_NO_PASSWORD', 'N')).upper() in ('1', 'Y', 'S', 'YES', 'SIM'):
    password_hub = ''
    password_intra = ''

ALLOWED_HOSTS = ['10.9.8.89', '10.9.8.88', 'localhost', '127.0.0.1', 'eia1ferramentas.a1.ind.br','devel-eia1ferramentas.a1.ind.br']

#  CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = tuple([f'http://{item}:8000' if not ('fer' in item) else f'http://{item}:8443' for item in
                               ALLOWED_HOSTS])

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'weba1',
    'english_platform',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'weba1.urls'

# Em settings.py para ambiente de desenvolvimento
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'weba1.wsgi.application'
# ASGI_APPLICATION = "weba1.asgi.application"

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)],
#         },
#     },
# }

#SESSION_COOKIE_AGE = 3 * 3600  # 3 horas a duração da session
#SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Evita avisos de chave primária auto-criada (Django 3.2+)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'C:/Users/alex.santos/Desktop/ProjetoEmily/EMProject/htdocs/static'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

#STATICFILES_DIRS = (os.path.join(BASE_DIR, 'staticfiles'),)


MEDIA_URL = '/media_/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_TIMEZONE = timezone('America/Sao_Paulo')
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

task_exchange = Exchange('default', type='direct')
task_exchange_dwg = Exchange('files_dwg', type='direct')

CELERY_TASK_QUEUES = (
    Queue('default', task_exchange, routing_key='default'),
    Queue('files_using_dwg', task_exchange_dwg, routing_key='files_dwg'),
)

CELERY_TASK_DEFAULT_QUEUE = 'default'
queue_files_dwg = {'queue': 'files_using_dwg'}

CELERY_TASK_ROUTES = {
    'eletrica.convert_dwgs_in_images_and_register': queue_files_dwg,
    'eletrica.funcao_dwg_diagram_inter': queue_files_dwg,
    'eletrica.insert_datas_doc_in_dwgs': queue_files_dwg, # verificar se está em uso!
    'eletrica.tipicos.percorre_dwg': queue_files_dwg,
    'eletrica.register_file_block_insert': queue_files_dwg,
    'eletrica.register_file_block_insert_band_elet': queue_files_dwg,
    'eletrica.register_file_template_gt': queue_files_dwg,
    'eletrica.gera_caderno_tipicos': queue_files_dwg, # Não esta sendo usado.
    'eletrica.rev_tipicos': queue_files_dwg,
}

CELERY_ALWAYS_EAGER = False
CELERY_ACKS_LATE = True
CELERY_TASK_PUBLISH_RETRY = True
CELERY_DISABLE_RATE_LIMITS = False

# CELERY_TIMEZONE = 'UTC'
# CELERY_ENABLE_UTC = True
CELERY_RESULT_EXPIRES = None  # celery.backend_cleanup por padrão limpa as tarefas todos os dias 4 da manhã
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'  # NÃO USAR

CELERY_BEAT_SCHEDULE = {
    'atualiza_layouta1_removendo_usuarios_desativados': {
        'task': 'geral.atualiza_layouta1_removendo_usuarios_desativados',
        'schedule': crontab(minute=15, hour=6)
    },
    'aniversario_sche': {
        'task': 'geral.update_table_aniv_schedule',
        'schedule': crontab(minute=0, hour=3)
    },
    'logs_vpn': {
        'task': 'geral.tasks.busca_api',
        'schedule': crontab(minute=15, hour=2),
        'args': (2,),
    },
    'atualiza_user_civil': {
        'task': 'A1Flex.update_users',
        'schedule': crontab(minute=0, hour=2)
    },
    'exec_pdms_pnc': {
        'task': 'engenharia.exec_pdms_pnc',
        'schedule': crontab(minute=0, hour=4)
    },
    'cg_to_per': {
        'task': 'a1hub.intranet_to_hub_cg',
        'schedule': crontab(minute=40, hour=3),
    },
    'os_to_so': {
        'task': 'a1hub.intranet_to_hub_os',
        'schedule': crontab(minute=30, hour=3),
    },
    'test-auto-bar': {
        'task': 'a1hub.task_test.go_to_sleep',
        'schedule': crontab(minute=0, hour=1),
        'args': (5, 2)
    },
    'clear_temp': {
        'task': 'a1hub.task_test.clear_temp',
        'schedule': crontab(minute=0, hour=0),
        'args': (30e10, 100)
    },
    # 'robodoc-auto-check': {
    #     'task': 'documentacao.a1pro_a1robodoc.check_files',
    #     'schedule': crontab(minute='*/20'),
    #     'args': (('robodoc', 'A1 teste', 'sea'), True),
    #     'kwargs': {'tipo_item': 30024, 'projeto': 30020},
    #     'options': {'time_limit': 960, 'expires': 960}
    # },
    'backup_dbs': {
        'task': 'weba1.utils.backup_dbs',
        'schedule': crontab(minute=0, hour=4),
        'args': False,
    },
    'dash_glpi': {
        'task': 'a1hub.send_reports_per_unit_to_managers',
        'schedule': crontab(minute=0, hour=6, day_of_month=1),
    },
    'cadastra_tags': {
        'task': 'eletrica.utils.register_tags_default_in_db_a1pro',
        'schedule': crontab(minute=0, hour=23),
    },
    ####### verificar implementacao rotina comos ##########
    #'cadastra_tags': {
    #    'task': 'comos_a1pro.export_comos.py.rotina_exportacao_comos',
    #    'schedule': crontab(minute=0, hour=5),
    #},
    #######################################################
    #'update-history': {
    #    'task': 'documentacao.utils.update_history',
    #    'schedule': crontab(minute=0, hour=19)
    # },
    # 'listdoc-weekly-report': {
    #    'task': 'documentacao.a1pro_a1listdoc.week_report',
    #    'schedule': crontab(minute=00, hour=7, day_of_week=1),  # Toda segunda-feira às 07h00 da manhã
    # }
}

DATABASE_ROUTERS = []

CORS_ORIGIN_ALLOW_ALL = True  # configuração cors para aceitar requisições REST
CORS_ALLOW_CREDENTIALS = True

# Ensure logs directory exists
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    # other dictConfig keys here...
    'handlers': {
        'graypy': {
            'level': 'WARNING',
            'class': 'graypy.GELFTCPHandler',
            'host': 'deimos.a1.ind.br',
            'port': 514,
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'debug.log'),
        },
        'daphne_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'daphne.log'),  # Specify the path for Daphne logs
        },
    },
    'loggers': {
        'a1pro': {
            'handlers': ['graypy'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
    'daphne': {
        'handlers': ['daphne_file'],
        'level': 'DEBUG',
        'propagate': False,
    },
    'channels': {
        'handlers': ['daphne_file'],
        'level': 'DEBUG',
        'propagate': False,
    },
}

CELERY_IMPORTS = ('weba1.tasks', )


# ----------------------------------------------------------------------------------------------------------------------
# Configurações API .NET (C#) - Endpoints que fazem POST para a Minimal API (C#) e devolvem o JSON.
CSHARP_API_BASE = "http://localhost:5148"
CSHARP_API_ENDPOINTS = {
    "materials_list": "/cad/materials_list",
    "diag_inter": "/cad/diag_inter",
}

